import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Markdown Editor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang='en'>
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Roboto+Slab&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
        </head>
        <body>{children}</body>
      </html>
    </>
  )
}
